// Generated by CoffeeScript 1.6.2
(function() {
  var Point;

  Point = (function() {
    function Point(x, y) {
      this.x = x;
      this.y = y;
    }

    Point.prototype.distance = function(a, b) {
      return Math.sqrt((b.x - a.x) * (b.x - a.x) + (b.y - a.y) * (b.x - a.x));
    };

    return Point;

  })();

}).call(this);
