// Generated by CoffeeScript 1.6.2
(function() {
  var VEdge;

  VEdge = (function() {
    function VEdge(start, left, right) {
      this.start = start;
      this.left = left;
      this.right = right;
      this.end = null;
      this.f = (this.right.x - this.left.x) / (this.left.y - this.right.y);
      this.g = this.start.y - this.f * this.start.x;
      this.direction = new Point(this.right.y - this.left.y, -(this.right.x - this.left.x));
      this.B = new Point(this.start.x + this.direction.x, this.start.y + this.direction.y);
      this.intersected = false;
      this.isCounted = false;
      this.neighbour = null;
    }

    return VEdge;

  })();

}).call(this);
