// Generated by CoffeeScript 1.6.2
(function() {
  var VParabola;

  VParabola = (function() {
    function VParabola(site) {
      this.site = site;
      this.cEvent = null;
      this.parent = null;
      this.left = null;
      this.right = null;
      this.isLeaf = this.site != null;
    }

    VParabola.prototype.setLeft = function(p) {
      this.left = p;
      return p.parent = this;
    };

    VParabola.prototype.setRight = function(p) {
      this.right = p;
      return p.parent = this;
    };

    return VParabola;

  })();

}).call(this);
