// Generated by CoffeeScript 1.6.2
(function() {
  var VQueue;

  VQueue = (function() {
    function VQueue() {
      this.q = [];
    }

    VQueue.prototype.enqueue = function(p) {
      return this.q.push(p);
    };

    VQueue.prototype.dequeue = function() {
      this.q.sort(function(a, b) {
        return a.y - b.y;
      });
      return this.q.pop();
    };

    VQueue.prototype.remove = function(e) {
      var i, index, qe, _i, _len, _ref;

      index = -1;
      _ref = this.q;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        qe = _ref[i];
        if (qe === e) {
          index = i;
          break;
        }
      }
      return this.q.splice(index, 1);
    };

    VQueue.prototype.isEmpty = function() {
      return this.q.length === 0;
    };

    VQueue.prototype.clear = function() {
      return this.q = [];
    };

    return VQueue;

  })();

}).call(this);
